version: "3"
services:
  postgres:
    image: timescale/timescaledb:latest-pg15
    ports:
      - 5439:5432
    environment:
      POSTGRES_DB: kayord
      POSTGRES_USER: kayord
      POSTGRES_PASSWORD: bbHRro5Ju2L9cw
    volumes:
      - timescale:/var/lib/postgresql/data
    restart: unless-stopped

  mosquitto:
    container_name: mosquitto
    image: eclipse-mosquitto:latest
    ports:
      - 1883:1883
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - ./config/mosquitto/mosquitto.conf:/mosquitto/config/mosquitto.conf:ro
      - ./config/mosquitto/mqtt_passwd:/mosquitto/config/mqtt_passwd:ro
      - mosquitto:/mosquitto/data
    restart: unless-stopped

volumes:
  timescale:
  mosquitto:
