version: "3"
services:
  postgres:
    image: timescale/timescaledb:latest-pg15
    ports:
      - 5439:5432
    environment:
      POSTGRES_DB: kayord
      POSTGRES_USER: kayord
      POSTGRES_PASSWORD: bbHRro5Ju2L9cw
    volumes:
      - timescale:/var/lib/postgresql/data

volumes:
  timescale:
